package woven_bank;

import java.io.BufferedWriter;
import java.io.FileWriter;

// Start of user code for imports
// End of user code

/**
 * Logger class definition.
 * Generated by the TouchCORE code generator.
 */
class Logger {
    
    protected boolean fileEnabled;
    protected boolean screenEnabled;
    protected String logTimeMessage;
    protected String logMessage;
    protected Account myLoggable;
    
    void setFile(boolean enable) {
        this.fileEnabled = enable;
    }

    void logToFile(String LogMessage, String filepath) throws Exception{
        BufferedWriter writer = new BufferedWriter(new FileWriter(filepath, true));
        writer.append(LogMessage);
        writer.close();
    }

    boolean getFileEnabled() {
        return this.fileEnabled;
    }

    void setScreen(boolean enable) {
        /* TODO: No message view defined */
         this.screenEnabled = enable;
    }

    void logToScreen(String logMessage) {
        System.out.println(logMessage);
    }

    boolean getScreenEnabled() {
        return this.screenEnabled;
    }

    Logger() {
        /* TODO: No message view defined */
    }

    void setLoggerTime(String message) {
        this.logTimeMessage = message;
    }

    String getLoggerTime() {
        return this.logTimeMessage;
    }

    void setLogMessage(String message) {
        this.logMessage = message;
    }

    String getLogMessage() {
        return this.logMessage;
    }

    boolean setMyLoggable(Account newObject) {
        Account oldAssociated = getMyLoggable();
        if (oldAssociated != null) {
            boolean unsetOld = oldAssociated.setSimpleMyLogger(null);
            if (!unsetOld) {
                return false;
            }
        }
        boolean setNew = newObject.setSimpleMyLogger(this);
        if (!setNew) {
            return false;
        }
        this.myLoggable = newObject;
        return true;
    }

    protected boolean setSimpleMyLoggable(Account newObject) {
        this.myLoggable = newObject;
        return true;
    }

    Account getMyLoggable() {
        return this.myLoggable;
    }
}
