package woven_bank;

// Start of user code for imports
// End of user code

/**
 * LoggableException class definition.
 * Generated by the TouchCORE code generator.
 */
class LoggableException {
    
    Account create() {
        /* TODO: No message view defined */
        return null;
    }
}
